name: lab7
description: A new Flutter project.


publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  intl: ^0.17.0
  xml2json: ^5.3.2
  shelf_cors_headers: ^0.1.3
  http: 0.13.4
  dio: ^4.0.6

dev_dependencies:
  flutter_cors: 1.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true


